CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER,
    NOMBRE NVARCHAR2(100),
    CIUDAD NVARCHAR2(100),
    CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO NUMBER,
    FECHA DATE,
    MONTO NUMBER,
    CLIENTE_ID NUMBER,
    CONSTRAINT PEDIDO_PK PRIMARY KEY(ID_PEDIDO),
    CONSTRAINT CLIENTE_FK FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(ID_CLIENTE)
);

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE VALUES(1,'JAVIER','MEXICO');
INSERT INTO CLIENTE VALUES(2,'FERNANDO','MONTERREY');
INSERT INTO CLIENTE VALUES(3,'OSCAR','CANCUN');
INSERT INTO CLIENTE VALUES(4,'MARIA','GUADALAJARA');
INSERT INTO CLIENTE VALUES(5,'GUADALUPE','JALISCO');
INSERT INTO CLIENTE VALUES(6,'SUSANA','MEXICO');

SELECT * FROM PEDIDO;

INSERT INTO PEDIDO VALUES(1,TO_DATE('15/08/2025', 'DD/MM/YYYY'),500.00,2);
INSERT INTO PEDIDO VALUES(2,TO_DATE('21/03/2025', 'DD/MM/YYYY'),200.00,2);
INSERT INTO PEDIDO VALUES(3,TO_DATE('12/02/2023', 'DD/MM/YYYY'),430.00,1);
INSERT INTO PEDIDO VALUES(4,TO_DATE('10/10/2025', 'DD/MM/YYYY'),2355.00,4);
INSERT INTO PEDIDO VALUES(5,TO_DATE('01/12/2025', 'DD/MM/YYYY'),5647.34,5);
INSERT INTO PEDIDO VALUES(6,TO_DATE('31/10/2025', 'DD/MM/YYYY'),353.34,NULL);

--1.CLIENTES QUE TIENEN PEDIDOS Y MONTOS DE CADA PEDIDO
SELECT NOMBRE,ID_PEDIDO,MONTO FROM CLIENTE C
INNER JOIN PEDIDO P
ON c.id_cliente = p.cliente_id;

--2.MOSTRAR TODOS LOS CLIENTES Y SUS PEDIDOS
SELECT * FROM CLIENTE C
LEFT JOIN PEDIDO P
ON c.id_cliente = p.cliente_id;


--3.TODOS LOS CLIENTES QUE NO TIENEN PEDIDOS
SELECT NOMBRE,ID_PEDIDO FROM CLIENTE C
LEFT JOIN PEDIDO P
ON C.ID_CLIENTE = p.cliente_id
WHERE P.ID_PEDIDO IS NULL;

--4.MOSTRAR TODOS LOS PEDIDO Y EL CLIENTE AL QUE PERTENECEN Y AUQNUE NO TENGA CLIENTE
SELECT * FROM PEDIDO P
LEFT JOIN CLIENTE C
ON P.CLIENTE_ID = C.ID_CLIENTE;

--5.
SELECT ID_PEDIDO,NOMBRE FROM PEDIDO P
LEFT JOIN CLIENTE C
ON C.ID_CLIENTE = p.cliente_id
WHERE c.id_cliente IS NULL;

--6.
SELECT * FROM PEDIDO P
FULL JOIN CLIENTE C
ON c.id_cliente = p.id_pedido;

--7.
SELECT * FROM PEDIDO P
FULL JOIN CLIENTE C
ON p.cliente_id = C.ID_CLIENTE
WHERE p.cliente_id IS NULL;