CREATE OR REPLACE FUNCTION SUMA (A IN NUMBER, B IN NUMBER)
RETURN NVARCHAR2
IS
    RESULTADO NVARCHAR2(100);
    R NUMBER;
BEGIN
    R := A + B;
    RESULTADO := 'EL RESULTADO DE LA SUMA ES: '||R;
    RETURN RESULTADO;
END SUMA;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(SUMA(10,20));
END;
/

SELECT SUMA(2,5) FROM DUAL;


--FUNCION QUE CALCULE EL AREA DE UN CIRCULO Y RECIBE COMO PARAMETRO EL RADIO
CREATE OR REPLACE FUNCTION A_CIRCULO (RADIO IN NUMBER)
RETURN NVARCHAR2
IS
    RESULTADO NVARCHAR2(100);
    AREA NUMBER;
BEGIN
    AREA := 3.1416 * POWER(RADIO,2);
    RESULTADO := 'EL AREA DEL CIRCULO ES: '||AREA;
    
    RETURN RESULTADO;
END A_CIRCULO;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(A_CIRCULO(5));
END;
/

SELECT a_circulo(40) FROM DUAL;


--CALCULAR EDAD APARTIR DE LA FECHA DE NACIMIENTO
CREATE OR REPLACE FUNCTION C_EDAD(F_NACIMIENTO IN DATE)
RETURN NVARCHAR2
IS
    RESULTADO NVARCHAR2(100);
    EDAD NUMBER;
BEGIN
    EDAD := TRUNC((SYSDATE - F_NACIMIENTO)/ 365);
    RESULTADO := 'LA EDAD DE LA PERSONA ES: '||EDAD;
    RETURN RESULTADO;
END C_EDAD;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(C_EDAD(DATE '2002-08-02'));
END;
/

SELECT C_EDAD(DATE '2002-08-02') FROM DUAL;



--CREAR UNA FUNCION QUE RECIBA UN PARAMETRO DEL 1 AL 12 RETORNE EL NOMBRE DEL CORRESPONDIENTE
CREATE OR REPLACE FUNCTION NOMBRE_MES (P_MES IN NUMBER)
RETURN NVARCHAR2
IS
    V_MES NVARCHAR2(20);
BEGIN
    CASE P_MES
        WHEN 1  THEN V_MES := 'ENERO';
        WHEN 2  THEN V_MES := 'FEBRERO';
        WHEN 3  THEN V_MES := 'MARZO';
        WHEN 4  THEN V_MES := 'ABRIL';
        WHEN 5  THEN V_MES := 'MAYO';
        WHEN 6  THEN V_MES := 'JUNIO';
        WHEN 7  THEN V_MES := 'JULIO';
        WHEN 8  THEN V_MES := 'AGOSTO';
        WHEN 9  THEN V_MES := 'SEPTIEMBRE';
        WHEN 10 THEN V_MES := 'OCTUBRE';
        WHEN 11 THEN V_MES := 'NOVIEMBRE';
        WHEN 12 THEN V_MES := 'DICIEMBRE';
        ELSE
            V_MES := 'INGRESA UN NUMERO QUE NO SEA MAYOR A 12';
    END CASE;

    RETURN V_MES;
END NOMBRE_MES;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(NOMBRE_MES(5));
END;
/

SELECT NOMBRE_MES(8) FROM DUAL;