CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO NUMBER,
    NOMBRE NVARCHAR2(100),
    LABORATORIO NVARCHAR2(100),
    PRECIO NUMBER,
    STOCK NUMBER,
    CONSTRAINT MEDICAMENTO_PK PRIMARY KEY(ID_MEDICAMENTO)
);

INSERT INTO MEDICAMENTO VALUES (1, 'PARACETAMOL', 'GENFAR', 15, 120);
INSERT INTO MEDICAMENTO VALUES (2, 'IBUPROFENO', 'BAYER', 22, 85);
INSERT INTO MEDICAMENTO VALUES (3, 'AMOXICILINA', 'PFIZER', 35, 60);
INSERT INTO MEDICAMENTO VALUES (4, 'ASPIRINA', 'BAYER', 18, 100);
INSERT INTO MEDICAMENTO VALUES (5, 'LORATADINA', 'SANOFI', 25, 70);
INSERT INTO MEDICAMENTO VALUES (6, 'NAPROXENO', 'ROCHE', 30, 55);
INSERT INTO MEDICAMENTO VALUES (7, 'AZITROMICINA', 'PFIZER', 45, 40);
INSERT INTO MEDICAMENTO VALUES (8, 'OMEPRAZOL', 'ASTRAZENECA', 28, 90);
INSERT INTO MEDICAMENTO VALUES (9, 'METFORMINA', 'MERCK', 32, 65);
INSERT INTO MEDICAMENTO VALUES (10, 'LOSARTAN', 'NOVARTIS', 38, 50);
INSERT INTO MEDICAMENTO VALUES (11, 'ENALAPRIL', 'ROCHE', 27, 80);
INSERT INTO MEDICAMENTO VALUES (12, 'INSULINA', 'NOVO NORDISK', 120, 30);
INSERT INTO MEDICAMENTO VALUES (13, 'DICLOFENACO', 'GENOMMA LAB', 20, 110);
INSERT INTO MEDICAMENTO VALUES (14, 'RANITIDINA', 'GLAXOSMITHKLINE', 24, 75);
INSERT INTO MEDICAMENTO VALUES (15, 'CLORFENAMINA', 'SANOFI', 16, 95);
INSERT INTO MEDICAMENTO VALUES (16, 'SALBUTAMOL', 'GLAXOSMITHKLINE', 40, 45);
INSERT INTO MEDICAMENTO VALUES (17, 'ATORVASTATINA', 'PFIZER', 55, 35);
INSERT INTO MEDICAMENTO VALUES (18, 'KETOROLACO', 'ROCHE', 26, 85);
INSERT INTO MEDICAMENTO VALUES (19, 'ACETAMINOFEN', 'BAYER', 14, 130);
INSERT INTO MEDICAMENTO VALUES (20, 'VITAMINA C', 'GENOMMA LAB', 12, 150);

SELECT * FROM MEDICAMENTO;

--1. SUMAR INVENTARIO
create or replace NONEDITIONABLE PROCEDURE AUMENTAR_STOCK(NOM IN NVARCHAR2 ,A_STOCK IN NUMBER) --ESTE PARAMETRO ME VA A INDICAR EL % DE DESC
IS
BEGIN
    UPDATE MEDICAMENTO
    SET STOCK = STOCK + A_STOCK
    WHERE NOMBRE = NOM;

    --IMPRIMIR MENSAJE PARA INDICAR QUE SI SE APLICO EL CAMBIO
    DBMS_OUTPUT.PUT_LINE('SE AÑADIERON: '||A_STOCK||' AL STOCK DEL MEDICAMENTO: '||NOM);
END AUMENTAR_STOCK;
/


--2.DESCUENTO DE STOCK
create or replace NONEDITIONABLE PROCEDURE DESCUENTO_STOCK(NOM IN NVARCHAR2 ,D_STOCK IN NUMBER) --ESTE PARAMETRO ME VA A INDICAR EL % DE DESC
IS
    STOCK_ACTUAL NUMBER;
    VAL NUMBER;
BEGIN
    SELECT STOCK INTO STOCK_ACTUAL FROM MEDICAMENTO WHERE NOMBRE = NOM;
    
    VAL := STOCK_ACTUAL - D_STOCK;
    
    IF VAL < 0 THEN
        DBMS_OUTPUT.PUT_LINE('NO EXISTE STOCK SUFICIENTE');
    ELSE
        UPDATE MEDICAMENTO SET
        STOCK = VAL
        WHERE NOMBRE = NOM;
        DBMS_OUTPUT.PUT_LINE('STOCK ACTUALIZADO: STOCK ATERIOR:'||STOCK_ACTUAL||' NUEVO STOCK:'||VAL);
    END IF;
    
END DESCUENTO_STOCK;
/

--3.ELIMINAR CON ID
CREATE OR REPLACE PROCEDURE ELIMINAR(ID_BORRAR IN NUMBER)
IS
BEGIN
    DELETE FROM MEDICAMENTO WHERE ID_MEDICAMENTO = ID_BORRAR ;

END ELIMINAR;
/

--4.DESCUENTO
CREATE OR REPLACE PROCEDURE DESCUENTO(P_DESCUENTO IN NUMBER)
IS
BEGIN

    UPDATE MEDICAMENTO
    SET PRECIO = PRECIO - (PRECIO * (P_DESCUENTO / 100));
    
    DBMS_OUTPUT.PUT_LINE('DESCUENTO APLICADO');


END DESCUENTO;
/



--PRUEBAS
SELECT * FROM MEDICAMENTO;

EXECUTE ELIMINAR(2);

EXECUTE aumentar_stock('PARACETAMOL', 20);

EXECUTE descuento_stock('PARACETAMOL', 20);

EXECUTE DESCUENTO(5);