CREATE TABLE TRABAJADOR(
    ID_TB NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    SALARIO NUMBER,
    CONSTRAINT TRABAJADOR_PK PRIMARY KEY(ID_TB)
);

INSERT INTO TRABAJADOR VALUES (1, 'CARLOS', 'HERNANDEZ', 35, 'GERENTE', 'ADMINISTRACION', 25000);
INSERT INTO TRABAJADOR VALUES (2, 'MARIA', 'LOPEZ', 28, 'CONTADOR', 'FINANZAS', 18000);
INSERT INTO TRABAJADOR VALUES (3, 'JUAN', 'PEREZ', 40, 'SUPERVISOR', 'PRODUCCION', 22000);
INSERT INTO TRABAJADOR VALUES (4, 'ANA', 'MARTINEZ', 26, 'ASISTENTE', 'RECURSOS HUMANOS', 15000);
INSERT INTO TRABAJADOR VALUES (5, 'LUIS', 'GOMEZ', 32, 'TECNICO', 'MANTENIMIENTO', 17000);
INSERT INTO TRABAJADOR VALUES (6, 'FERNANDA', 'RAMIREZ', 29, 'ANALISTA', 'SISTEMAS', 20000);
INSERT INTO TRABAJADOR VALUES (7, 'RICARDO', 'TORRES', 45, 'DIRECTOR', 'DIRECCION', 30000);
INSERT INTO TRABAJADOR VALUES (8, 'JORGE', 'HERNDEZ', 43, 'JEFE DE DEPARTAMENTO', 'SISTEMAS', 20000);
INSERT INTO TRABAJADOR VALUES (9, 'ANGEL', 'GARCIA', 20, 'PRACTICANTE', 'SISTEMAS', 5000);
INSERT INTO TRABAJADOR VALUES (10, 'JOSE', 'MARTINEZ', 20, 'PRACTICANTE', 'MANTENIMIENTO', 5000);

SELECT * FROM TRABAJADOR;

COMMIT;

--VISTA MUSTRA SOLO LOS TRABAJADORES DE SISTEMAS
CREATE VIEW V_TBSISTEMAS AS
SELECT ID_TB, NOMBRE, APELLIDO, EDAD, PUESTO, DEPARTAMENTO, SALARIO FROM TRABAJADOR WHERE DEPARTAMENTO = 'SISTEMAS';

SELECT * FROM V_TBSISTEMAS;

--VISTA CON TRABAJADORES CON SUELDO MAYOR A 10000
CREATE VIEW V_TBMAYORSUELDO AS
SELECT ID_TB, NOMBRE, APELLIDO, EDAD, PUESTO, DEPARTAMENTO, SALARIO FROM TRABAJADOR WHERE SALARIO > 10000;

SELECT * FROM v_tbmayorsueldo;

--VISTA SALARIO TIPO ALTO, MEDIO, BAJO
CREATE VIEW V_TB_CATEGORIA_SALARIO AS
SELECT ID_TB, NOMBRE, APELLIDO, EDAD, PUESTO, DEPARTAMENTO,
(
    CASE 
    WHEN SALARIO < 10000 THEN 'EL EMPLEADO GANA: '||SALARIO||' Y ES UN SUELDO BAJO'
    WHEN SALARIO >= 10000 AND SALARIO < 20000 THEN 'EL EMPLEADO GANA: '||SALARIO||' Y ES UN SUELDO MEDIO'
    WHEN SALARIO >= 20000 THEN 'EL EMPLEADO GANA: '||SALARIO||' Y ES UN SUELDO ALTO'
    END
    
)AS SALARIO FROM TRABAJADOR;

SELECT * FROM v_tb_categoria_salario;