CREATE TABLE BIT_ESTUDIANTE_MOV(
    ID_BIT_MOV NUMBER,
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_ESTUDIANTE_MOV_PK PRIMARY KEY(ID_BIT_MOV)
    
);

--TRIGGER A NIVEL SENTENCIA
CREATE OR REPLACE TRIGGER TR_S_MULTIPLE_ESTUDIANTE
AFTER INSERT OR UPDATE OR DELETE ON ESTUDIANTE
--CUANDO ES UN TRIGGER A NIVEL SENTENCIA NO SE ESCRIBE EL FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    --RECUPERAR DATOS DEL SISTEMA Y UN ID VALIDO
    SELECT SEQ_ESTUDIANTE.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
        INSERT INTO BIT_ESTUDIANTE_MOV(ID_BIT_MOV, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END TR_S_MULTIPLE_ESTUDIANTE;
/

--PRUEBAS 
SELECT * FROM ESTUDIANTE;
SELECT * FROM BIT_ESTUDIANTE;
SELECT * FROM BIT_ESTUDIANTE_MOV;

INSERT INTO ESTUDIANTE VALUES(1,'GUSTAVO','CONTRERAS', 23, 'MECATRONICA', 8,9,8.6);
INSERT INTO ESTUDIANTE VALUES(4,'JUAN','PEREZ', 24, 'ARQUITECTURA', 8,3,9.6);

DELETE FROM ESTUDIANTE;
DELETE FROM BIT_ESTUDIANTE;
DELETE FROM BIT_ESTUDIANTE_MOV;