CREATE OR REPLACE PROCEDURE PR_TRABAJADOR
IS
    --1. DECLARAR CURSOR
    CURSOR TRABAJADOR_INFO IS
    
        SELECT NOMBRE, SALARIO FROM TRABAJADOR;  
            --VARIABLES
            LV_NOMBRE TRABAJADOR.NOMBRE%TYPE;
            LV_SALARIO NUMBER;
BEGIN
     --2.ABRIR EL CURSOR
     OPEN TRABAJADOR_INFO;
     
     --3.RESUPERAR EL CURSOR
     LOOP
        --RECORRER CADA FILA
        FETCH TRABAJADOR_INFO INTO LV_NOMBRE, LV_SALARIO;
        --CONDICION SALIR CUANDO YA NO ENCUENTRE INFORMACION
        EXIT WHEN TRABAJADOR_INFO%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE('NOMBRE DEL TRABAJADOR: '||LV_NOMBRE||', SU SALARIO ES: '||LV_SALARIO);
        
        END LOOP;
    --4. CERRAR LOOP
        CLOSE TRABAJADOR_INFO;
END PR_TRABAJADOR;
/

BEGIN
    PR_TRABAJADOR;
END;
/

SELECT * FROM TRABAJADOR;


---------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PR_ESTUDIANTE
IS
    --1. DECLARAR CURSOR
    CURSOR ESTUDIANTE_INFO IS
    
        SELECT NOMBRE, CARRERA FROM ESTUDIANTE WHERE CARRERA = 'SISTEMAS';  
            --VARIABLES
            LV_NOMBRE ESTUDIANTE.NOMBRE%TYPE;
            LV_CARRERA NVARCHAR2(100);
BEGIN
     --2.ABRIR EL CURSOR
     OPEN ESTUDIANTE_INFO;
     
     --3.RESUPERAR EL CURSOR
     LOOP
        --RECORRER CADA FILA
        FETCH ESTUDIANTE_INFO INTO LV_NOMBRE, LV_CARRERA;
        --CONDICION SALIR CUANDO YA NO ENCUENTRE INFORMACION
        EXIT WHEN ESTUDIANTE_INFO%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE('NOMBRE DEL ESTUDIANTE: '||LV_NOMBRE||', DE LA CARRERA: '||LV_CARRERA);
        
        END LOOP;
    --4. CERRAR LOOP
        CLOSE ESTUDIANTE_INFO;
END PR_ESTUDIANTE;
/

SELECT * FROM ESTUDIANTE;

BEGIN
    PR_ESTUDIANTE;
END;
/