CREATE TABLE ESTUDIANTE(
    ID_ESTUDIANTE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    CARRERA NVARCHAR2(100),
    CREDITOS NUMBER,
    SEMESTRE NUMBER,
    PROMEDIO NUMBER,
    CONSTRAINT ESTUDIANTE_PK PRIMARY KEY(ID_ESTUDIANTE)
);

COMMIT;

CREATE TABLE BIT_ESTUDIANTE(
    ID_BIT NUMBER,
    
    ID_ESTUDIANTE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    CARRERA NVARCHAR2(100),
    CREDITOS NUMBER,
    SEMESTRE NUMBER,
    PROMEDIO NUMBER,
    
    NOMBRE_OLD NVARCHAR2(100),
    APELLIDO_OLD NVARCHAR2(100),
    EDAD_OLD NUMBER,
    CARRERA_OLD NVARCHAR2(100),
    CREDITOS_OLD NUMBER,
    SEMESTRE_OLD NUMBER,
    PROMEDIO_OLD NUMBER,
    
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_ESTUD_PK PRIMARY KEY(ID_BIT)
); 

--secuencia
CREATE SEQUENCE SEQ_ESTUDIANTE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--TRIGGER
CREATE OR REPLACE TRIGGER TR_MULTIPLE_ESTUDIANTE
AFTER INSERT OR UPDATE OR DELETE ON ESTUDIANTE
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    SELECT SEQ_ESTUDIANTE.NEXTVAL,USER,SYSDATE INTO LV_ID_BIT,LV_USUARIO,LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        INSERT INTO BIT_ESTUDIANTE(ID_BIT,ID_ESTUDIANTE,NOMBRE,APELLIDO,EDAD,CARRERA,CREDITOS,SEMESTRE,PROMEDIO,
        NOMBRE_OLD,APELLIDO_OLD,EDAD_OLD,CARRERA_OLD,CREDITOS_OLD,SEMESTRE_OLD,PROMEDIO_OLD,
        USUARIO,FECHA_MOV,MOVIMIENTO)
        VALUES(LV_ID_BIT,:NEW.ID_ESTUDIANTE, :NEW.NOMBRE, :NEW.APELLIDO, :NEW.EDAD, :NEW.CARRERA,:NEW.CREDITOS, :NEW.SEMESTRE, :NEW.PROMEDIO,
        NULL,NULL,0,NULL,0,0,0,
        LV_USUARIO,LV_FECHA,'INSERT');
        
    ELSIF DELETING THEN
        INSERT INTO BIT_ESTUDIANTE(ID_BIT,ID_ESTUDIANTE,NOMBRE,APELLIDO,EDAD,CARRERA,CREDITOS,SEMESTRE,PROMEDIO,
        NOMBRE_OLD,APELLIDO_OLD,EDAD_OLD,CARRERA_OLD,CREDITOS_OLD,SEMESTRE_OLD,PROMEDIO_OLD,
        USUARIO,FECHA_MOV,MOVIMIENTO)
        VALUES(LV_ID_BIT, :OLD.ID_ESTUDIANTE, NULL, NULL, 0, NULL, 0, 0, 0,
        :OLD.NOMBRE, :OLD.APELLIDO, :OLD.EDAD, :OLD.CARRERA, :OLD.CREDITOS, :OLD.SEMESTRE, :OLD.PROMEDIO,
        LV_USUARIO,LV_FECHA,'DELETE');
        
    ELSIF UPDATING THEN
        INSERT INTO BIT_ESTUDIANTE(ID_BIT,ID_ESTUDIANTE,NOMBRE,APELLIDO,EDAD,CARRERA,CREDITOS,SEMESTRE,PROMEDIO,
        NOMBRE_OLD,APELLIDO_OLD,EDAD_OLD,CARRERA_OLD,CREDITOS_OLD,SEMESTRE_OLD,PROMEDIO_OLD,
        USUARIO,FECHA_MOV,MOVIMIENTO)
        VALUES(LV_ID_BIT,:OLD.ID_ESTUDIANTE, :NEW.NOMBRE, :NEW.APELLIDO, :NEW.EDAD, :NEW.CARRERA, :NEW.CREDITOS, :NEW.SEMESTRE, :NEW.PROMEDIO,
        :OLD.NOMBRE, :OLD.APELLIDO, :OLD.EDAD, :OLD.CARRERA, :OLD.CREDITOS, :OLD.SEMESTRE, :OLD.PROMEDIO,
        LV_USUARIO,LV_FECHA,'UPDATE');
        
    END IF;
END TR_MULTIPLE_ESTUDIANTE;
/


--PRUEBAS
SELECT * FROM ESTUDIANTE;

SELECT * FROM BIT_ESTUDIANTE;

INSERT INTO ESTUDIANTE VALUES (1,'JUAN','HERNANDEZ',21,'SISTEMAS COMPUTACIONALES',10,5,9.0);
INSERT INTO ESTUDIANTE VALUES (2,'ANGEL','CONTRERAS',22,'ARQUITECTURA',8,6,8.9);
INSERT INTO ESTUDIANTE VALUES (3,'GUSTAVO','GARCIA',23,'SISTEMAS COMPUTACIONALES',5,8,8.5);

DELETE FROM ESTUDIANTE WHERE NOMBRE = 'JUAN';

UPDATE ESTUDIANTE SET
    NOMBRE = 'FRANCISCO',
    APELLIDO = 'MARTINEZ',
    PROMEDIO = '7.5'
WHERE ID_ESTUDIANTE = 3;

COMMIT;

--lipiar tablas
delete from estudiante;
delete from bit_estudiante;