--1: CREAR TABLA
CREATE TABLE ALUMNO(
    ID_ALUMNO NUMBER,
    NOMBRE NVARCHAR2 (100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    CARRERA NVARCHAR2(100),
    PROMEDIO NUMBER,
    GENERO NVARCHAR2(1),
    CONSTRAINT ALUMNO_PK PRIMARY KEY(ID_ALUMNO)
);
--2.INSERTAR DATOS
INSERT INTO ALUMNO VALUES(1,'DANIEL', 'SANCHEZ', 22, 'SISTEMAS COMPUTACIONALES', 8.7, 'M');
INSERT INTO ALUMNO VALUES(2,'GUSTAVO', 'CONTRERAS', 23, 'SISTEMAS COMPUTACIONALES', 8.4, 'M');
INSERT INTO ALUMNO VALUES(3,'ANA', 'ORTEGA', 34, 'ARQUITECTURA', 7.8, 'F');
INSERT INTO ALUMNO VALUES(4,'ERIS', 'MORENO', 21, 'AERONAUTICA', 8.8, 'F');
INSERT INTO ALUMNO VALUES(5,'FERNANDO', 'RAMIREZ', 18, 'LOGISTICA', 7.7, 'M');
INSERT INTO ALUMNO VALUES(6,'JHONATAN', 'GARCIA', 25, 'AUTOMOTRIZ', 9.6, 'M');
INSERT INTO ALUMNO VALUES(7,'BRENDA', 'MARTINEZ', 21, 'CONTABILIDAD', 8.7, 'F');
INSERT INTO ALUMNO VALUES(8,'VALERIA', 'CASTILLO', 29, 'INFORMATICA', 7.5, 'F');

--3.REALIZAR CONSULTAS
COMMIT;

--1.MOSTRAR TODOS LOS ALUMNOS REGISTRADOS
SELECT * FROM ALUMNO;

--2.MOSTRAR EL NOMBRE Y CARRERA DE TODOS LOS ALUMNOS;
SELECT NOMBRE, CARRERA FROM ALUMNO;

--3.MOSTRAR LOS NOMBRE Y PROMEDIO MAYOR A 8
SELECT NOMBRE, PROMEDIO FROM ALUMNO WHERE PROMEDIO > 8;

--4.MOSTRAR A LOS ALUMNOS QUE PERMANECEN A LA CARRERA DE SISTEMAS
SELECT NOMBRE, CARRERA FROM ALUMNO WHERE CARRERA = 'SISTEMAS COMPUTACIONALES';

--5.MOSTRAR CUYA EDAD SEA MAYOR O IGAUL A 22 A;OS
SELECT NOMBRE,EDAD FROM ALUMNO WHERE EDAD > 21;

--6.ORDENADOS POR APELIDO DE LA A-Z
SELECT * FROM ALUMNO ORDER BY APELLIDO ASC;

--7.MOSTRAR LOS ALUMNOS MUJERES
SELECT * FROM ALUMNO WHERE GENERO = 'F';

--8.MOSTRAR POR PROMEDOIO DEL MAS BAJO AL MAS ALTO
SELECT * FROM ALUMNO ORDER BY PROMEDIO ASC;

--9.CONTAR CUANTOS ALUMNOS HAY EN TOTAL
SELECT COUNT(ID_ALUMNO) AS TOTAL_ALUMNOS FROM ALUMNO;

--10.CONTAR CUNATOS ALUMNOS HAY POR CARRERA
SELECT CARRERA, COUNT(ID_ALUMNO) AS TOTAL_ALUMNOS FROM ALUMNO WHERE CARRERA IN ('SISTEMAS COMPUTACIONALES', 'ARQUITECTURA','CONTABILIDAD','AERONAUTICA','LOGISTICA','AUTOMOTRIZ') GROUP BY CARRERA;

--11.MOSTRAR EL PROMEDIO GENERAL DE LOS ALUMNOS
SELECT ROUND(AVG(PROMEDIO),2) AS PROMEDIO_ALUMNOS FROM ALUMNO;

--12.MEJOR PROMEDIO
SELECT * FROM ALUMNO WHERE PROMEDIO = (SELECT MAX(PROMEDIO) AS PROMEDIO_MAXIMO FROM ALUMNO);

--13.PEOR PROMEDIO
SELECT * FROM ALUMNO WHERE PROMEDIO = (SELECT MIN(PROMEDIO) AS PROMEDIO_MINIMO FROM ALUMNO);

--14.PROMEDIO EDAD DE LOS ALUMNOS DE SISTEMAS
SELECT ROUND(AVG(EDAD),2) AS PROMEDIO_EDAD_INFORMATICA FROM ALUMNO WHERE CARRERA = 'INFORMATICA';

--15.MOSTRAR CUANTOS HOMBRES Y CUANTAS MUJERES HAY
SELECT GENERO, COUNT(ID_ALUMNO) AS TOTAL_GENEROS FROM ALUMNO WHERE GENERO IN('M','F') GROUP BY GENERO;

--16.ALUMNO CUYO APELLIDO INICIA CON M
SELECT * FROM ALUMNO WHERE APELLIDO LIKE 'M%';

--17.FORMATO PIPE
SELECT 'EL ALUMNO(A) '||NOMBRE||' '||APELLIDO||' CON LA EDAD DE '||EDAD||' AÑOS, ESTUDIA '
||CARRERA||' CON PROMEDIO DE '||PROMEDIO AS PIPE_ALUMNO FROM ALUMNO;