SELECT * FROM ESTUDIANTE;
SELECT * FROM MATERIA;
SELECT * FROM CALIFICACION;

COMMIT;
--CREAR UNA TABLA MATERIA
CREATE TABLE MATERIA(
    ID_MATERIA NUMBER,
    NOMBRE_MT NVARCHAR2(100),
    CREDITOS NUMBER,
    CONSTRAINT MATERIA_PK PRIMARY KEY(ID_MATERIA)
);

--CREAR TABLA CALIFICACION
CREATE TABLE CALIFICACION(
    ID_CALIFICACION NUMBER,
    ESTUDIANTE_ID NUMBER,
    MATERIA_ID NUMBER,
    CALIFICACION NUMBER,
    CONSTRAINT CALIFICACION_PK PRIMARY KEY(ID_CALIFICACION),
    CONSTRAINT ESTUDIANTE_FK FOREIGN KEY(ESTUDIANTE_ID) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
    CONSTRAINT MATERIA_FK FOREIGN KEY(MATERIA_ID) REFERENCES MATERIA(ID_MATERIA)
);

--INSERT DE DATOS 
INSERT INTO MATERIA VALUES (1, 'Matemáticas', 8);
INSERT INTO MATERIA VALUES (2, 'Programación', 10);
INSERT INTO MATERIA VALUES (3, 'Base de Datos', 9);
INSERT INTO MATERIA VALUES (4, 'Redes', 7);
INSERT INTO MATERIA VALUES (5, 'Ingeniería de Software', 8);

INSERT INTO CALIFICACION VALUES(1,1,1,8.7);
INSERT INTO CALIFICACION VALUES(2,1,2,9.7);
INSERT INTO CALIFICACION VALUES(3,2,3,8.5);
INSERT INTO CALIFICACION VALUES(4,2,4,9.0);
INSERT INTO CALIFICACION VALUES(5,3,5,8.3);
INSERT INTO CALIFICACION VALUES(6,3,4,7.8);
INSERT INTO CALIFICACION VALUES(7,4,2,8.7);
INSERT INTO CALIFICACION VALUES(8,4,1,9.5);
INSERT INTO CALIFICACION VALUES(9,5,2,10.0);
INSERT INTO CALIFICACION VALUES(10,5,4,7.9);
INSERT INTO CALIFICACION VALUES(11,6,5,8.4);
INSERT INTO CALIFICACION VALUES(12,6,3,8.9);
INSERT INTO CALIFICACION VALUES(13,7,2,8.1);
INSERT INTO CALIFICACION VALUES(14,7,4,9.3);
INSERT INTO CALIFICACION VALUES(15,8,3,7.4);
INSERT INTO CALIFICACION VALUES(16,8,1,8.5);
INSERT INTO CALIFICACION VALUES(17,9,2,8.7);
INSERT INTO CALIFICACION VALUES(18,9,4,8.2);
INSERT INTO CALIFICACION VALUES(19,10,5,9.9);
INSERT INTO CALIFICACION VALUES(20,10,2,8.8);

--A. MUESTRA EL NOMBRE COMPLETO DEL ESTUDIANTE, MATERIA Y SU CALIFICACION
CREATE OR REPLACE VIEW NC_MATERIA_CAL AS
SELECT 
    NOMBRE || ' ' || APELLIDO AS NOMBRE_COMPLETO,
    NOMBRE_MT AS MATERIA,
    CALIFICACION
FROM CALIFICACION C
INNER JOIN ESTUDIANTE E
    ON C.ESTUDIANTE_ID = E.ID_ESTUDIANTE
INNER JOIN MATERIA M
    ON C.MATERIA_ID = M.ID_MATERIA;

SELECT * FROM nc_materia_cal;

--B.CREAR UNA VISTA QUE MUESTRE EL PROMEDIO DE CADA ALUMNO, SEGUN EN LA CALIFICACION DE LAS MATERIAS
CREATE OR REPLACE VIEW M_PROMEDIO AS
SELECT 
    NOMBRE,
    AVG(C.CALIFICACION) AS PROMEDIO
FROM CALIFICACION C
INNER JOIN ESTUDIANTE E
ON C.ESTUDIANTE_ID = E.ID_ESTUDIANTE GROUP BY NOMBRE;

SELECT * FROM m_promedio;


--C.UNA VISTA QUE MUESTRE EL PROMEDIO POR MATERIA
CREATE OR REPLACE VIEW PROMEDIO_X_MATERIA AS
SELECT
    NOMBRE_MT AS MATERIA,
    AVG(CALIFICACION) AS PROMEDIO
FROM CALIFICACION C
INNER JOIN MATERIA M 
ON C.MATERIA_ID = M.ID_MATERIA GROUP BY NOMBRE_MT;

SELECT * FROM promedio_x_materia;


--D.ALUMNOS CON PROMEDIO SUPERIOR AL GENERAL
CREATE OR REPLACE VIEW CALIF_X_MATERIA AS
SELECT
    NOMBRE,
    PROMEDIO_ALUMNO,
    PROMEDIO_GENERAL
FROM (
    SELECT
        NOMBRE,
        AVG(CALIFICACION) AS PROMEDIO_ALUMNO,
        (SELECT AVG(CALIFICACION) FROM CALIFICACION) AS PROMEDIO_GENERAL
    FROM CALIFICACION C
    JOIN ESTUDIANTE E
    ON C.ESTUDIANTE_ID = E.ID_ESTUDIANTE GROUP BY NOMBRE
)
WHERE PROMEDIO_ALUMNO > PROMEDIO_GENERAL;

SELECT * FROM calif_x_materia;


--E. SEGUN LA CALIFICACION POR MATERIA, CLASIFICANDO EL DESEMPE;O DE LOS ALUMNOS(EXELENTE, BUENO, REGULAR)
CREATE OR REPLACE VIEW CLASIFICACION_DESEMPENO AS
SELECT
    NOMBRE AS ALUMNO,
    NOMBRE_MT AS MATERIA,
    CALIFICACION,
    CASE
        WHEN CALIFICACION >= 9 THEN 'EXCELENTE'
        WHEN CALIFICACION >= 7 THEN 'BUENO'
        ELSE 'REGULAR'
    END AS DESEMPENO
FROM CALIFICACION C
INNER JOIN ESTUDIANTE E    ON C.ESTUDIANTE_ID = E.ID_ESTUDIANTE
INNER JOIN MATERIA M
ON C.MATERIA_ID = M.ID_MATERIA;

SELECT * FROM CLASIFICACION_DESEMPENO;