CREATE TABLE PRD_ESTUDIANTE(
    ID_ESTUDIANTE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    CARRERA NVARCHAR2(100),
    CREDITOS NUMBER,
    SEMESTRE NUMBER,
    PROMEDIO NUMBER,
    CONSTRAINT PR_ESTUDIANTE_PK PRIMARY KEY(ID_ESTUDIANTE)
);

SELECT * FROM ESTUDIANTE;
SELECT * FROM PRD_ESTUDIANTE;

INSERT INTO ESTUDIANTE VALUES(1,'MARIA','LOPEZ', 22, 'SISTEMAS', 9,8,9.2);
INSERT INTO ESTUDIANTE VALUES(2,'CARLOS','RAMIREZ', 25, 'MECATRONICA', 7,8,8.1);
INSERT INTO ESTUDIANTE VALUES(3,'ANA','MARTINEZ', 21, 'ARQUITECTURA', 9,9,9.5);
INSERT INTO ESTUDIANTE VALUES(4,'LUIS','HERNANDEZ', 23, 'CIVIL', 8,7,8.4);
INSERT INTO ESTUDIANTE VALUES(5,'FERNANDA','GOMEZ', 24, 'SISTEMAS', 9,8,9.0);
INSERT INTO ESTUDIANTE VALUES(6,'JORGE','CASTILLO', 26, 'MECATRONICA', 7,6,7.8);
INSERT INTO ESTUDIANTE VALUES(7,'PAOLA','VARGAS', 22, 'ARQUITECTURA', 8,9,8.9);
INSERT INTO ESTUDIANTE VALUES(8,'DANIEL','RODRIGUEZ', 23, 'CIVIL', 8,8,8.6);
INSERT INTO ESTUDIANTE VALUES(9,'SOFIA','MENDOZA', 21, 'SISTEMAS', 9,9,9.7);
INSERT INTO ESTUDIANTE VALUES(10,'RICARDO','TORRES', 24, 'MECATRONICA', 8,7,8.3);


--RESPALDO
CREATE OR REPLACE PROCEDURE PR_RESPALDO_ESTUDIANTE
IS
--DECLARACION DE VARIABLES CONSTANTES O CURSORES
BEGIN
    --PARA PODER REUTILIZAR ESTE PROCEDIMIENTO, PRIMERO LIMPIAMOS LA TABLA COMPUTADORA_PRD
    DELETE FROM PRD_ESTUDIANTE;
    
    --RESPALDO DE COMPUTADORA2 EN COMPUTADORA_PRD
    INSERT INTO PRD_ESTUDIANTE(ID_ESTUDIANTE, NOMBRE, APELLIDO, EDAD, CARRERA, CREDITOS, SEMESTRE, PROMEDIO)
    SELECT ID_ESTUDIANTE, NOMBRE, APELLIDO, EDAD, CARRERA, CREDITOS, SEMESTRE, PROMEDIO FROM ESTUDIANTE;
END PR_RESPALDO_ESTUDIANTE;
/

--PRUEBAS
SELECT * FROM ESTUDIANTE;
SELECT * FROM PRD_ESTUDIANTE;

DELETE FROM ESTUDIANTE;

EXECUTE pr_respaldo_estudiante;

