CREATE TABLE SALA(
    ID_SALA NUMBER,
    NOMBRE NVARCHAR2(100),
    CAPACIDAD NUMBER,
    TIPO NUMBER,--1.TRADICIONAL, 2.VIP, 3.IMAX
    CONSTRAINT SALA_PK PRIMARY KEY(ID_SALA)
);

CREATE TABLE FUNCION(
    ID_FUNCION NUMBER,
    PELICULA NVARCHAR2(100),
    DURACION_MIN NUMBER,
    GENERO NVARCHAR2(100),
    PRECIO_BOLETO NUMBER,
    SALA_ID NUMBER,
    CONSTRAINT FUNCION_PK PRIMARY KEY(ID_FUNCION),
    CONSTRAINT SALA_FK FOREIGN KEY(SALA_ID) REFERENCES SALA(ID_SALA)
);

SELECT * FROM SALA;

INSERT INTO SALA VALUES(1,'SALA NEO', 200,1);
INSERT INTO SALA VALUES(2,'SALA ECLIPCE', 300,3);
INSERT INTO SALA VALUES(3,'SALA ADROMEDA', 250,2);
INSERT INTO SALA VALUES(4,'SALA VENECIA', 300,3);
INSERT INTO SALA VALUES(5,'SALA FANTASY', 200,1);
INSERT INTO SALA VALUES(6,'SALA PIXELES', 200,1);
INSERT INTO SALA VALUES(7,'SALA NEPTUNO', NULL,NULL);

SELECT * FROM FUNCION;

INSERT INTO FUNCION VALUES(1,'LOS GUARDIANES DE LA GALAXIA', 120,'CIENCIA FICCION', 40,1);
INSERT INTO FUNCION VALUES(2,'GUARDIANES DE LA NOCHE', 280,'ANIMACION', 32.99,6);
INSERT INTO FUNCION VALUES(3,'SIMBAD', 160,'CIENCIA FICCION', 38.00,3);
INSERT INTO FUNCION VALUES(4,'LA MASCARA', 220,'COMEDIA', 21.99,3);
INSERT INTO FUNCION VALUES(5,'EL CONJURO', 270,'TERROR', 35.77,4);
INSERT INTO FUNCION VALUES(6,'MATRIX', 120,'ACCION', 44,2);
INSERT INTO FUNCION VALUES(7,'MISION IMPOSIBLE', 220,'ACCION', 34.66,NULL);

COMMIT;

--1.MOSTRAR TODAS LA FUNCIONES CON EL NOMBRE DE LA SALA Y EL TIPO DE SALA USANDO CASE.
SELECT ID_FUNCION,PELICULA,NOMBRE,
(
    CASE TIPO
    WHEN 1 THEN 'TRADICIONAL'
    WHEN 2 THEN 'VIP'
    WHEN 3 THEN 'IMAX'
    ELSE 'SIN ESPECIFICAR'
    END
)AS TIPO_SALA FROM FUNCION F
LEFT JOIN SALA S
ON f.sala_id = s.id_sala ORDER BY ID_FUNCION ASC;

--2.CONTAR CUANTAS FUNCIONES HAY POR EGENRO
SELECT GENERO, COUNT(ID_FUNCION) AS TOTAL_FUNCIONES
FROM FUNCION
GROUP BY GENERO;

--3.MOSTRAR LA FUNCION CON EL BOLETO MAS CARO Y AGREGAR LA PALABRA "PESOS" AL FINAL
SELECT ID_FUNCION, PELICULA,GENERO, DURACION_MIN,
    CONCAT(PRECIO_BOLETO, ' PESOS') AS PRECIO_TEXTO
FROM FUNCION
WHERE PRECIO_BOLETO = (
    SELECT MAX(PRECIO_BOLETO)
    FROM FUNCION
);

--4.MOSTRAR EL TOTAL DE BOLETOS QUE PODRIA VENDFER CADA FUNCION(CAPACIDAD DE LA SALA * PRECIO BOLETO)
SELECT ID_FUNCION, CAPACIDAD, PRECIO_BOLETO,
    (CAPACIDAD * PRECIO_BOLETO) AS TOTAL
FROM FUNCION f
INNER JOIN SALA s
ON f.sala_id = s.id_sala;

--5.-MOSTRAR LA SALA CON MAYOR ACPACIDAD Y CONCATENAR EL RESULTADO CON LA PALBRA "AISENTOS"
SELECT ID_SALA, NOMBRE,
    CONCAT(CAPACIDAD, ' ASIENTOS') AS CAPACIDAD
FROM SALA
WHERE CAPACIDAD = (
    SELECT MAX(CAPACIDAD)
    FROM SALA
);
--6.MOSTRAR LAS FUNCIONES QUE NO TIENEN SALA ASIGNADA
SELECT * FROM FUNCION F
LEFT JOIN SALA S
ON f.sala_id = s.id_sala
WHERE F.sala_id is null;

--7.ORDENAR LAS FUNCIONAS PRIMEROS POR GENERO Y LUEGO POR DURACION(ES SOLO UN CONSULTA)
SELECT * FROM FUNCION ORDER BY GENERO,DURACION_MIN;

--8.MOSTRAR EL DETALLE DE LAS FUNCIONES CON PIPES || "LA PELICULA EL TITANICA SE PROYECTA EN LA SALA VIVALDI DE TIPO VIP CON UNA DURACION DE 120 MINUTOS"
SELECT 'LA PELICULA '||PELICULA||' SE PROYECTARA EN LA SALA '||NOMBRE||' DE TIPO '
||(
    CASE TIPO
    WHEN 1 THEN 'TRADICIONAL'
    WHEN 2 THEN 'VIP'
    WHEN 3 THEN 'IMAX'
    ELSE 'SIN ESPECIFICAR'
    END
)||
' CON UNA DURACION '||DURACION_MIN||'MINUTOS' AS DETALLE FROM FUNCION F
FULL JOIN SALA S
ON f.sala_id = s.id_sala;

--9.MOSTRAR EL GENERO QUE MAS FUNCIONES REGISTRADAS TIENE
SELECT * FROM (
    SELECT genero, COUNT(*) AS total_funciones
    FROM FUNCION
    GROUP BY genero
    ORDER BY total_funciones DESC
)
WHERE ROWNUM = 1;

