CREATE TABLE COMPUTADORA(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    RAM NUMBER,
    ALMACENAMIENTO NUMBER,
    PROCESADOR NVARCHAR2(100),
    TIPO NUMBER, --1.ESCRITORIO, 2.PORTATIL, 3.TABLET, 4.TODOENUNO
    PRECIO NUMBER,
    FECHA DATE,
    CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPU)
);

INSERT INTO COMPUTADORA VALUES (1, 'Dell', 16, 512, 'Intel Core i7', 2, 18000, TO_DATE('15-07-2024','DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (2, 'HP', 8, 256, 'Intel Core i5', 1, 14500, TO_DATE('10-11-2023','DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (3, 'Lenovo', 16, 1024, 'AMD Ryzen 7', 2, 19500, TO_DATE('05-03-2024','DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (4, 'Apple', 8, 512, 'M1', 4, 28000, TO_DATE('20-09-2022','DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (5, 'Samsung', 6, 128, 'Exynos', 3, 9500, TO_DATE('01-06-2023','DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (6, 'Asus', 32, 1024, 'Intel Core i9', 1, 32000, TO_DATE('18-09-2024','DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (7, 'Acer', 8, 512, 'AMD Ryzen 5', 2, 16000, TO_DATE('08-12-2023','DD-MM-YYYY'));

SELECT * FROM computadora;

COMMIT;

--1.CLASIFICA LAS COMPUTADORAS POR CAPACIDAD DE RAM
SELECT ID_COMPU, MARCA,
(
    CASE
    WHEN RAM < 8 THEN 'BAJA'
    WHEN RAM >= 8 AND RAM <= 16 THEN 'MEDIA'
    WHEN RAM > 16 THEN 'ALTA'
    ELSE 'SIN CLASIFICAR'
    END
)AS RAM, ALMACENAMIENTO, PROCESADOR, TIPO, PRECIO, FECHA FROM COMPUTADORA;

--2.CLASIFICA LAS COMPUTADORAS POR PRECIO
SELECT ID_COMPU, MARCA, RAM, ALMACENAMIENTO, PROCESADOR, TIPO,
(
    CASE
    WHEN PRECIO <= 18000 THEN 'PRECIO BAJO'
    WHEN PRECIO >18000 AND PRECIO <= 28000 THEN 'PRECIO ESTANDAR'
    WHEN PRECIO >28000 THEN 'PRECIO CARO'
    ELSE 'SIN CLASIFICAR'
    END
)AS PRECIO, FECHA FROM computadora;


--3.CLSIFICA LAS COMPUTADORAS POR CAPACIDAD DE ALMACENAMIENTO
SELECT ID_COMPU, MARCA, RAM,
(
    CASE
    WHEN ALMACENAMIENTO <= 256 THEN 'POCO ALMACENAMIENTO'
    WHEN ALMACENAMIENTO > 256 AND ALMACENAMIENTO <= 512 THEN 'ALMACANAMIENTO ESTANDAR'
    WHEN ALMACENAMIENTO > 512 THEN 'ALTO ALMACENAMIENTO'
    ELSE 'SIN ESPECIFICAR'
    END
)AS ALMACENAMIENTO, PROCESADOR, TIPO, PRECIO, FECHA FROM COMPUTADORA;

--4.MUESTRA LA INFORMACION DE LA COMPU CON SU RESPECTIVO TIPO
SELECT ID_COMPU, MARCA, RAM, ALMACENAMIENTO, PROCESADOR,
(
    CASE TIPO
    WHEN 1 THEN 'ESCRITORIO'
    WHEN 2 THEN 'PORTATIL'
    WHEN 3 THEN 'TABLET'
    WHEN 4 THEN 'TODO EN UNO'
    ELSE 'SIN DEFINIR'
    END
)AS TIPO, PRECIO,FECHA FROM COMPUTADORA ORDER BY TIPO ASC;

--5.CLASIFICA LAS COMPUTADORAS POR ANTIGUEDAD
SELECT ID_COMPU, MARCA, RAM, ALMACENAMIENTO, PROCESADOR, TIPO, PRECIO,
(
    CASE
    WHEN FECHA < '31/12/2022' THEN 'MUY ANTIGUA'
    WHEN FECHA < '31/12/2023' THEN 'POCO ANTIGUA'
    WHEN FECHA < '31/12/2024' THEN 'RECIENTE'
    ELSE 'SIN DEFINIR'
    END
)AS ANTIGUEDAD FROM COMPUTADORA ORDER BY FECHA ASC;
