--TRIGGER A NIVEL SENTENCIA (STATENMENT): SE EJECUTA UNA VEZ POR SENTEMCIA

--BITACORA QUE SOLO ME REGISTRE EL MOVIMIENTO, USUARIO Y FECHA

CREATE TABLE BIT_COMPU_MOV(
    ID_BIT_MOV NUMBER,
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_COMPU_MOV_PK PRIMARY KEY(ID_BIT_MOV)
    
);

--TRIGGER A NIVEL SENTENCIA
CREATE OR REPLACE TRIGGER TR_S_MULTIPLE_COMPU
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA2
--CUANDO ES UN TRIGGER A NIVEL SENTENCIA NO SE ESCRIBE EL FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    --RECUPERAR DATOS DEL SISTEMA Y UN ID VALIDO
    SELECT S_ID_BIT.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
        INSERT INTO BIT_COMPU_MOV(ID_BIT_MOV, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END TR_S_MULTIPLE_COMPU;
/

--PRUEBAS 
SELECT * FROM COMPUTADORA2;
SELECT * FROM BIT_COMPU_MOV;
SELECT * FROM BIT_COMPUTADORA2;

INSERT INTO COMPUTADORA2 VALUES(5,'DELL','INSPIRION', 8, 'INTEL CORE 12TH', 7000);

DELETE FROM COMPUTADORA2;