/*PROCEDIMIENTO ALMACENADO (): ES UN BLOQUE DE CODIGO SQL QUE SE GUARDA Y EJECUTA DIRECTAMENTE EN EL SERVIDOR DE LA BASE DE DATOS
ES UNA UNIDAD REUTILIZABLE DE PROGRAMACION QUE REALIZA TAREAS COMO CONSULTAS, INSERCIONES, ACTUALIZACIONES, VALIDACIONES Y MAS

PARA QUE SIRVE?
SIRVE PARA AUTOMATIZAR TAREAS RESOECTIVAS EN LA BASE DE DATOS, COMO

    -VALIDAR DATOS ANTES DE INSERTARLOS
    -ACTUALIZAR VARIAS TABLAS
    -GENERAR REPORTES
    -SIMPLIFICAR LA LOGICA EN LAS APLICACIONES
    -MEJORA EL RENDIMIENTO Y SEGURIDAD
    
VENTAJAS DE USAR PROCEDIMEINTO ALMACENADO
    -REDUCE EL TRAFICO ENTRE LA APLICACION Y LA BASE DE DATOS
    -
    
*/

INSERT INTO COMPUTADORA2 VALUES (1, 'HP', 'Pavilion 15', 8, 'Intel Core i5', 14500);
INSERT INTO COMPUTADORA2 VALUES (2, 'Dell', 'Inspiron 14', 16, 'Intel Core i7', 18900);
INSERT INTO COMPUTADORA2 VALUES (3, 'Lenovo', 'ThinkPad E14', 8, 'AMD Ryzen 5', 16500);
INSERT INTO COMPUTADORA2 VALUES (4, 'Asus', 'VivoBook 15', 12, 'Intel Core i5', 15800);
INSERT INTO COMPUTADORA2 VALUES (5, 'Acer', 'Aspire 5', 16, 'AMD Ryzen 7', 19500);
INSERT INTO COMPUTADORA2 VALUES (6, 'HP', 'Envy 13', 16, 'Intel Core i7', 22000);
INSERT INTO COMPUTADORA2 VALUES (7, 'Dell', 'XPS 13', 16, 'Intel Core i7', 28000);
INSERT INTO COMPUTADORA2 VALUES (8, 'Lenovo', 'IdeaPad 3', 8, 'AMD Ryzen 3', 12000);
INSERT INTO COMPUTADORA2 VALUES (9, 'Asus', 'ROG Strix', 32, 'Intel Core i9', 45000);
INSERT INTO COMPUTADORA2 VALUES (10, 'Acer', 'Nitro 5', 16, 'AMD Ryzen 7', 25000);

INSERT INTO COMPUTADORA2 VALUES (11, 'HP', 'ProBook 450', 8, 'Intel Core i5', 17500);
INSERT INTO COMPUTADORA2 VALUES (12, 'Dell', 'Latitude 5420', 16, 'Intel Core i7', 23500);
INSERT INTO COMPUTADORA2 VALUES (13, 'Lenovo', 'Yoga Slim 7', 16, 'AMD Ryzen 7', 26000);
INSERT INTO COMPUTADORA2 VALUES (14, 'Asus', 'ZenBook 14', 16, 'Intel Core i7', 27000);
INSERT INTO COMPUTADORA2 VALUES (15, 'Acer', 'Swift 3', 8, 'Intel Core i5', 16000);
INSERT INTO COMPUTADORA2 VALUES (16, 'HP', 'Victus 16', 32, 'AMD Ryzen 9', 38000);
INSERT INTO COMPUTADORA2 VALUES (17, 'Dell', 'G15 Gaming', 16, 'Intel Core i7', 29000);
INSERT INTO COMPUTADORA2 VALUES (18, 'Lenovo', 'Legion 5', 32, 'AMD Ryzen 7', 35000);
INSERT INTO COMPUTADORA2 VALUES (19, 'Asus', 'TUF F15', 16, 'Intel Core i7', 26500);
INSERT INTO COMPUTADORA2 VALUES (20, 'Acer', 'Predator Helios', 32, 'Intel Core i9', 48000);

SELECT * FROM COMPUTADORA2;

--REALIZAR UN RESPALDO DE LA TABLA COMPUTADORA EN OTRA TABLA

--CREAR LA TABLA PARA CREAR EL RESPALDO
CREATE TABLE COMPUTADORA_PRD(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PRD_PK PRIMARY KEY(ID_COMPU)
);

SELECT * FROM COMPUTADORA_PRD;

CREATE OR REPLACE PROCEDURE PR_RESPALDO_COMPUTADORA
IS
--DECLARACION DE VARIABLES CONSTANTES O CURSORES
BEGIN
    --PARA PODER REUTILIZAR ESTE PROCEDIMIENTO, PRIMERO LIMPIAMOS LA TABLA COMPUTADORA_PRD
    DELETE FROM COMPUTADORA_PRD;
    
    --RESPALDO DE COMPUTADORA2 EN COMPUTADORA_PRD
    INSERT INTO COMPUTADORA_PRD(ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO)
    SELECT ID_COMPU2, MARCA, MODELO, RAM, PROCESADOR, PRECIO FROM COMPUTADORA2;
END PR_RESPALDO_COMPUTADORA;
/


SELECT * FROM COMPUTADORA2;
SELECT * FROM COMPUTADORA_PRD;

--EXECUTAR EL PROCEDIMIENTO
EXECUTE pr_respaldo_computadora;

--APLICAR UN DESCUENTO A TODOS LOS REGISTROS DE LA TABLA
CREATE OR REPLACE PROCEDURE APLICAR_DESCUENTOS(P_DESCUENTO IN NUMBER) --ESTE PARAMETRO ME VA A INDICAR EL % DE DESC
IS
BEGIN
    UPDATE COMPUTADORA2
    SET PRECIO = PRECIO - (PRECIO * (P_DESCUENTO / 100));
    
    --IMPRIMIR MENSAJE PARA INDICAR QUE SI SE APLICO EL CAMBIO
    DBMS_OUTPUT.PUT_LINE('SE APLICO UN DESCUENTO DEL: '||P_DESCUENTO||'% A TODAS LAS COMPUTADORAS');
END APLICAR_DESCUENTOS;
/

SELECT * FROM COMPUTADORA2;
EXECUTE aplicar_descuentos(10);