--VIISTAS COMPLEJAS

SELECT * FROM PADRE;

SELECT * FROM HIJO;

--MOSTRAR EL NOMNBRE DEL HIJO Y EL PADRE

CREATE OR REPLACE VIEW V_HIJO_PADRE AS
SELECT H.NOMBRE, P.NOMBRE AS PADRE
FROM HIJO H
INNER JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

SELECT * FROM v_hijo_padre;

--VISTAS USANDO FUNCIONES DE AGREGACION

--SUMA LOS EDADES DEL PADRE
CREATE OR REPLACE VIEW SUMA_TOTAL_EDADES AS
SELECT TRABAJO, SUM(EDAD) AS SUMA_EDADES
FROM PADRE
GROUP BY TRABAJO;

SELECT * FROM suma_total_edades;