/*TRIGGERS (DISPARADORES): ES UN BLOQUE DE CODIGO QUE SE EJECUTA AUTOMATICAMENTE EN RESPUESTA DE CIERTOS EVENTOS DE UNA TABLA O VISTA COMO:
-INSERT
-DELETE
-UPDATE

PARA QUE SE PUEDEN USAR LOS TRIGGERTS?
SIRVEN PARA: 
    -REGISTRAR AUDITORIAS(BITACORAS DE CAMBIO)
    -VALIDAR REGLAS DE NEGOCIO COMPLEJAS
    -MANTENER LA INTEGRIDAD DE LOS DATOS
    -GENERAR VALORES AUTOMATICOS (POR EJEMPLO TIMESTAP O USUARIO QUE MODIFICO)
TIPO DE TRIGGER
    -BEFORE -> SE EJECUTA ANTES DE QUE OCURRA LA OPERACION
    -AFTER -> SE EJECUTA DESPUES DE QUE OCURRA LA OPERACION
    -INSTEAD OF -> SE USA EN VISTAS,REMPLAZAMDO UNA OPERACION DML
    
NIVEL DEL TRIGGER
    -ROW (POR FILA): EL TRIGGER SE ACTIVA UNA VEZ POR CADA FILA AFECTADA
    -STATEMENT (POR SENTENCIA): EL TRIGGER SE ACTIVA UNA SOLA VEZ POR UNA INSTRUCCION SQL SIN IMPORTAR CUANTAS FILAS SE VEAN AFECTADAS
    
    --VARIABLES ESPECIALES (IDENTIFICADORES DE CORRELACION) QUE SE USA UNICAMENTE EN TRIGGER FOR EACH ROW (POR FILA)
        :OLD -> REPRESENTA LOS VALORES ANTERIORES (ANTES DE MODIFICAR)
        :NEW -> REPRESENTA LOS VALORES NUEVOS (DESPUES DE INSERTAR O MODIFICAR)
    SOLO FUNCIONAN EN TRIGGER FOR EACH ROW
*/

--REALIZAR UN TRIGGER DE TIPO AFTER FOR EACH ROW PARA REALIZAR LA AUDITORIA DE LOS MOVIMIENTOS QUE OPERAN SOBRE UNA TABLA

CREATE TABLE COMPUTADORA2(
    ID_COMPU2 NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT  COMPU2_PK PRIMARY KEY(ID_COMPU2)
);

--GENERAR UNA TABLA PARA REGISTRAR LOS MOVIMIENTOS OCURRIDOS EN LA TABLA COMPUTADORA

CREATE TABLE BIT_COMPUTADORA2(
    ID_BIT NUMBER,
    
    --CAMPOS DE COMPUTADORA
    --REPRESENTAN LOS VALORES NUEVOS(CUANDO OCURRA UN INSER O UPDATE)
    ID_COMPU2 NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    
    --REPRESENTA VALORES VIEJOS
    MARCA_OLD NVARCHAR2(100),
    MODELO_OLD NVARCHAR2(100),
    RAM_OLD NUMBER,
    PROCESADOR_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER,
    
    --CAMPOS PARA EL CONTROL (USUARIO, FECHA Y EL TIPO DE MOVIMIENTO QUE MODIFICO LA TABLA COMPUTADORA)
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_COMPU_PK PRIMARY KEY(ID_BIT)
);

--TRIGGER AFTER A NIVEL FILA SIMPLE
CREATE OR REPLACE TRIGGER TR_I_COMPUTADORA
AFTER INSERT ON COMPUTADORA2
FOR EACH ROW --TRIGGER A NIVEL FILA 
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR USUARIO
    SELECT USER INTO LV_USUARIO FROM DUAL;
    --RECUPERAR FECHA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;
    --RECUPERAR UN ID VALIDO EN AUTOINCREMENTO
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA2;

    INSERT INTO bit_computadora2(ID_BIT,ID_COMPU2,MARCA,MODELO,RAM,PROCESADOR,PRECIO,marca_old,modelo_old,ram_old,
                                PROCESADOR_OLD,PRECIO_OLD,USUARIO,fecha_mov,movimiento)
    VALUES(LV_ID_BIT, :NEW.ID_COMPU2,:NEW.MARCA,:NEW.MODELO,:NEW.RAM,:NEW.PROCESADOR,:NEW.PRECIO,NULL,NULL,0,NULL,0,LV_USUARIO,LV_FECHA,'INSERT');
END TR_I_COMPUTADORA;
/

--TRIGGER DELETE
CREATE OR REPLACE TRIGGER TR_DELETE2_COMPUTADORA
AFTER DELETE ON COMPUTADORA2
FOR EACH ROW 
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR USUARIO
    SELECT USER INTO LV_USUARIO FROM DUAL;

    --RECUPERAR FECHA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;

    --RECUPERAR UN ID VALIDO EN AUTOINCREMENTO
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA2;

    INSERT INTO BIT_COMPUTADORA2(ID_BIT, ID_COMPU2, MARCA, MODELO, RAM, PROCESADOR, PRECIO,MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT,:OLD.ID_COMPU2,NULL,NULL,0,NULL,0,:OLD.MARCA,:OLD.MODELO,:OLD.RAM,:OLD.PROCESADOR,:OLD.PRECIO,LV_USUARIO,LV_FECHA,'DELETE');
END TR_DELETE_COMPUTADORA;
/


--TRIGGER UPDATE
CREATE OR REPLACE TRIGGER TR_UPDATE_COMPUTADORA
AFTER UPDATE ON COMPUTADORA2
FOR EACH ROW --TRIGGER A NIVEL FILA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR USUARIO
    SELECT USER INTO LV_USUARIO FROM DUAL;

    --RECUPERAR FECHA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;

    --RECUPERAR UN ID VALIDO EN AUTOINCREMENTO
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA2;

    INSERT INTO BIT_COMPUTADORA2 (ID_BIT, ID_COMPU2, MARCA, MODELO, RAM, PROCESADOR, PRECIO,MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES(LV_ID_BIT,:OLD.ID_COMPU2,:NEW.MARCA,:NEW.MODELO,:NEW.RAM,:NEW.PROCESADOR,:NEW.PRECIO,:OLD.MARCA,:OLD.MODELO,:OLD.RAM,:OLD.PROCESADOR,:OLD.PRECIO,LV_USUARIO,LV_FECHA,'UPDATE');
END TR_UPDATE_COMPUTADORA;
/


--PRUEBAS
SELECT * FROM COMPUTADORA2;
SELECT * FROM bit_computadora2;
INSERT INTO COMPUTADORA2 VALUES(1,'HP','PAVILON',16,'INTEL CORE I9 12TH',15000);
INSERT INTO COMPUTADORA2 VALUES(2,'LENOVO','THINKPAD',8,'RYZEN 5 3500',8000);
INSERT INTO COMPUTADORA2 VALUES(3,'ACER','NITRO 5',12,'INTEL 3',6000);
INSERT INTO COMPUTADORA2 VALUES(4,'DELL','XPS 13',6,'INTEL 5',7500);

DELETE FROM COMPUTADORA2 WHERE MARCA = 'HP';
DELETE FROM COMPUTADORA2 WHERE MARCA = 'DELL';
DELETE FROM COMPUTADORA2 WHERE MARCA = 'ACER';

UPDATE COMPUTADORA2 SET 
    MARCA = 'SAMSUNG',
    PRECIO = 222222.99,
    RAM = 24,
    PROCESADOR = 'RYZEN 7 5500'
WHERE ID_COMPU2 = 1;