/*CURSOR ES UN MECANISMO QUE SE USA PL/SQL PARA RECORRER REGISTROS DE UNA CONSULTA
SQL DE FORMA FILA POR FILA

CUANDO EJECUTAS UN SELECT EN PL/SQL SE DEVUELVE UNA SOLA FILA PUEDE USAR WL SELECT..INTO
PEROS SU EL SELECT DEVULEVE VARIAS FILAS, NESESITAS UN CIRSOR PARA RECORRERLAS UNA A UNA

CURSORES IMPLICITOS
    SE CREAN AUTOMATICAMENTE CUANDO EJECUTAS UN INSERT, UPDATE, DELETE O SELECT INTO
    NO ES NECESARIO DECLEARLO
    
CURSORES EXPLICITOS
    LOS DECLARAS TU MISMO
    SE USAN PATA RECORRER RESULTADOS DE UN SELECT QUE DEVULEVE FILAS
    TIENE 4 PASOS A SEGUIR
    DECLARAR > ABRIR > RECUPERAR > CERRAR */
    
SELECT * FROM LIBRO;

CREATE OR REPLACE PROCEDURE PR_DETALLE_LIBRO
IS
    --1. DECLARAR CURSOR
    CURSOR LIBRO_INFO IS
        SELECT NOMBRE, (
            CASE GENERO
            --1.DRAMA, 2.TERROR, 3.CIENCIA FICCION, 4.NOVELA, 5.TRILLER
                WHEN 1 THEN 'DRAMA'
                WHEN 2 THEN 'TERROR'
                WHEN 3 THEN 'CIENCIA FICCION'
                WHEN 4 THEN 'NOVELA'
                WHEN 5 THEN 'TRILLER'
                ELSE 'SIN GENERO'
                END) AS GENERO, PRECIO FROM LIBRO;
            
            --VARIABLES
            LV_NOMBRE LIBRO.NOMBRE%TYPE;
            LV_GENERO NVARCHAR2(100);
            LV_PRECIO NUMBER;
BEGIN
     --2.ABRIR EL CURSOR
     OPEN LIBRO_INFO;
     
     --3.RESUPERAR EL CURSOR
     LOOP
        --RECORRER CADA FILA
        FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
        --CONDICION SALIR CUANDO YA NO ENCUENTRE INFORMACION
        EXIT WHEN LIBRO_INFO%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO: '||LV_NOMBRE||', ES DE GENERO '||LV_GENERO||' Y TIENE UN PRECIO DE '||LV_PRECIO);
        END LOOP;
    --4. CERRAR LOOP
        CLOSE LIBRO_INFO;
END PR_DETALLE_LIBRO;
/

BEGIN
    PR_DETALLE_LIBRO;
END;
/