--CLAUSULAS JOIN -> INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL JOIN

--CREAR CON DDL LA ENTIDAD DE PADRE
CREATE TABLE PADRE(
    ID_PADRE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    TRABAJO NVARCHAR2(100),
    CONSTRAINT PADRE_PK PRIMARY KEY (ID_PADRE)
);

INSERT INTO PADRE VALUES(1,'NICOLAS','MORALES',53,'DOCENTE');
INSERT INTO PADRE VALUES(2,'PEDRO','GARCIA',46,'PROFESOR');
INSERT INTO PADRE VALUES(3, 'DONATO', 'BARRERA', 54, 'DOCENTE');
INSERT INTO PADRE VALUES(4, 'SANDRA','PALMA', 33,'DIRECTORA');
INSERT INTO PADRE VALUES(5,'RAMIRO','JUAREZ',53,'DOCENTE');
INSERT INTO PADRE VALUES(6, 'PASCAR', 'RAMIREZ', 48, 'CONTADOR');
INSERT INTO PADRE VALUES(7, 'JOSE LUIS','BARRERA', 58, 'PROFESOR');

SELECT * FROM PADRE;

--GENERAR LA ENTIDAD HIJO
CREATE TABLE HIJO(
    ID_HIJO NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    HOBBIE NVARCHAR2(100),
    PADRE_ID NUMBER,
    CONSTRAINT HIJO_PK PRIMARY KEY(ID_HIJO),
    CONSTRAINT PADRE_FK FOREIGN KEY(PADRE_ID) REFERENCES PADRE(ID_PADRE)
    --CONTRAINT (PALABRA RESERVADA) + NOMBRE DEL CONTRAINT (UNICO) + TIPO CONSTRAIN (TIPODE KEY) + CAMPO EN LA TABLA
    --QUE SEA LA LLAVE FORANEA+REFERENCE(PA;ABRA RESERVADA)+EL NOMBRE DE LA TABLA Y EL CAMPO AL QUE SE HACE REFERENCIA
    --DE LA TABLA A LA QUE VOY CONECTAR(EN ESTE CASO ES PADRE)
);

INSERT INTO HIJO VALUES(1, 'ALINE', 'MORALES', 25, 'VER TELEVISION', 1);
INSERT INTO HIJO VALUES(2, 'JAVIER', 'CASTILLO', 12, 'JUGAR XBOX', NULL);
INSERT INTO HIJO VALUES(3, 'DANNAE', 'GARCIA', 25, 'ESCUCHAR MUSICA', 4);
INSERT INTO HIJO VALUES(4, 'DAMARIS', 'FLORES', 10, 'PINTAR', NULL);
INSERT INTO HIJO VALUES(5, ' EDUARDO', 'ANAYA ',24, 'JUGAR FUTBOL ',7);
INSERT INTO HIJO VALUES(6, 'VALERIA', 'GARCIA', 26, 'BAILAR', 3);
INSERT INTO HIJO VALUES(7,'ANGEL','GARCIA', 23, 'VOLEIBOL', 4);
INSERT INTO HIJO VALUES(8,'SOFIA','MARTINEZ', 27, 'NATACION', 6);

SELECT * FROM HIJO;

--USO DEL INNER JOIN -> DEVUELVE LOS REGISTROS COINCIDENCIAS DE AMBAS TABLAS
SELECT * FROM HIJO H
INNER JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;


--USO DE LEFT JOIN -> DEVUELVE 
SELECT * FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

SELECT * FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;


--USO RIGHT JOIM
SELECT * FROM HIJO H
RIGHT JOIN PADRE P
ON h.padre_id = P.ID_PADRE;

SELECT * FROM HIJO H
RIGHT JOIN PADRE P
ON h.padre_id = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;


--FULL JOIN
SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;
