/*VISTAS O VIEWS: ES UNA TABLA VIRTUAL QUE SE CREA APARRIR DE UNA CONSULTA SQL, NO ALMACENA DATOS
FISICAMENTE, SOLO GUARDA LA CONSULTA

    CUANDO CONSULTAS UNA VISTA LA BASE DE DATOS EJECUTA EL SELEC QUE LA DEFINE

PARA QUE SIRVE
    SIMPLIFICAR CONSULTAS COMPLEJAS
    REUTILIZAR CONSULTAS
    OCULTAR COLUMNAS SENSIBLES
    MEJORA LA SEGURIDAD
TIPOS DE VISTAS
    VISTAS SIMPLES; SE USAN PARA UN TBLAS NO TIENEN FUNCIONES DE AGREGACION
    VISTAS COMPLEJAS: USAN JOIN(DOS O MAS TABLAS) USAN FUNCIONES DE AGREGACION
    
*/

SELECT * FROM COMPUTADORA2;

CREATE VIEW V_COMPUS_BARATAS AS 
SELECT ID_COMPU2, MARCA, MODELO, PRECIO FROM COMPUTADORA2 WHERE PRECIO < 15000;

--CONSULTAR O USAR LA VISTA
SELECT * FROM v_compus_baratas;

--SELECCIONAR SOLO LA MARCA HP
CREATE VIEW V_COMPUS_MARCA AS
SELECT ID_COMPU2,MARCA, MODELO, PROCESADOR FROM COMPUTADORA2 WHERE MARCA = 'HP';

SELECT * FROM v_compus_marca;

--CLASIFICAR POR RAM
CREATE VIEW V_COMPU_CATEGORIA AS
SELECT ID_COMPU2, MARCA, MODELO,
(
    CASE 
    WHEN RAM < 16 THEN 'LA RAM ES '||RAM||' ES GAMA BAJA'
    WHEN RAM >= 16 AND RAM < 32 THEN 'LA RAM ES: '||RAM||' ES GAMA MEDIA'
    WHEN RAM = 32 THEN 'LA RAM ES: '||RAM||' ES GAMA ALTA'
    END
    
)AS RAM,
PROCESADOR, PRECIO FROM COMPUTADORA2;

SELECT * FROM v_compu_categoria;