--CONSULTAS BASICAS Y FUNCIONES DE AGREGACION;

INSERT INTO EMPLEADO VALUES(1,'DANIEL', 'GOMEZ', 24, 'GERENTE DE ADMINISTRACION', 'ADMINISTRACION');
INSERT INTO EMPLEADO VALUES(2,'JUAN', 'HERNANDEZ', 26, 'GERENTE DE FINANZAS', 'FINANZAS');
INSERT INTO EMPLEADO VALUES(3,'ROBERTO','FLORES',46,'GERENTE DE SISTEMAS','SISTEMAS');
insert into Empleado values(4, 'MARIO', 'GONZALEZ', 24, 'GERENTE DE MARKETING', 'PUBLICIDAD');
INSERT into Empleado values(5, 'WILIAM', 'ALCÁNTARA', 25, 'DISEÑADOR', 'IMAGEN');
insert into Empleado values(6, 'DANIEL', 'GARDUÑO', 40, 'GERENTE DE LOGISTICA', 'LOGISTICA');

COMMIT; --EN CASO DE NO COMFIRMAR LA BASE DE DATOS PUEDE BLOQUEARSE
ROLLBACK; -- EN CASO DE EQUIVOCARME ESTE REVIERTE LOS CAMBIOS

SELECT * FROM EMPLEADO;

--MODIFICAR EL CAMBIO DE LA COLUMNA EMPLEADO 
ALTER TABLE EMPLEADO RENAME COLUMN APP TO APELLIDO;

--DML ACTUALIZAR (UPDATE)
UPDATE EMPLEADO SET NOMBRE = 'JIMENA' WHERE ID_EMPLEADO = 6;

--FUNCION ORDER BY
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
SELECT * FROM EMPLEADO ORDER BY EDAD DESC;

--BUSQUEDA DE INFORAMCION CON CARACTERES ESPESIFICOS
--BUSCAR EMPLEADO QUE SU NOMBRE INICIA CON J
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'J%';

--BUSCAR EMPLEADOS QUE SU NOMBRE CONTENGA LA LETRA L
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%R%';

--BUSCAR EMPLEADOS QUE SU NOMBRE TERMINE CON LA LETRA O
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%O';

--USO DE LA TABLA DUAL: ES UNA TABLA QUE NOS OFRECE ORACLE Y QUE NOS PERMITE HACER OPRECIONES SIN LA NECESIDAD DE TENER UNA TABLA CREADA
SELECT 5 + 5 AS SUMA FROM DUAL;

--USO DE LA FUNCION LENGHT
SELECT LENGTH ('ESTA CADENA ES UNA PRUEBA PARA EL USO DE LENGTH') AS TAMANIO FROM DUAL;

--BUSCAR CON MAS CONDICIONES
--BUSCAR EMPLEADO MAYORES DE 25
SELECT * FROM EMPLEADO WHERE EDAD > 25;

--BUSCAR EMPLEADO MENORES DE 30;
SELECT * FROM EMPLEADO WHERE EDAD < 30;

--BUSCAR EMPLEADO QUE SEAN >24 PERO <28
SELECT * FROM EMPLEADO WHERE EDAD > 24 AND EDAD < 28;

--USAR EL RANGO BETWEEN
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 24 AND 28;

--BUSCAR LOS EMPLEADOS CON EL ID 1 Y 5;
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO = 1 OR ID_EMPLEADO = 5;

--DE LA FUNCION IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1,5);

--USO DE LA FUNCION GROUP BY Y COUNT
SELECT DEPARTAMENTO FROM EMPLEADO GROUP BY DEPARTAMENTO;

SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NO_EMPLEADO FROM EMPLEADO GROUP BY DEPARTAMENTO;

--CONTAR LOS EMPLEADOS MAYORES A 25
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADO FROM EMPLEADO WHERE EDAD > 25;

--USO DE LA FUNCION SUM
SELECT SUM(EDAD) AS SUMA_EDADES FROM EMPLEADO;

--FUNCION DE AGREGACION MAX
SELECT MAX(EDAD) AS EDAD_MAXIMA FROM EMPLEADO;

--FUNCION MIN
SELECT MIN(EDAD) AS EDAD_MIN FROM EMPLEADO;

--FUNCION AVG(AVERAGE)
SELECT AVG(EDAD) AS EDAD_PROMEDIO FROM EMPLEADO;

--FUNCION ROUND
SELECT ROUND(AVG(EDAD),2) AS PROMEDIO_EDAD_REDONDEADO FROM empleado;

--USO DE TO_CHAR CON FORMATO
SELECT TO_CHAR(AVG(EDAD), 'fm999.0') AS PROMEDIO_EDAD FROM EMPLEADO;

--DAR UN FORMATO DIFERENTE 
--USO DE CONCAT
SELECT CONCAT(CONCAT(CONCAT(CONCAT('EL EMPLEADO', ' '), NOMBRE), ' '), APELLIDO) AS DETALLE FROM EMPLEADO;

--USO DE LOS 'PIPE' O BARRA VERTICALES --> ||
SELECT 'EL EMPLEADO(A) '||NOMBRE||' '||APELLIDO||' CON LA EDAD DE '||EDAD||' AÑOS, TRABAJA EN EL DEPARTAMENTO DE '
||DEPARTAMENTO||' COMO '||PUESTO AS DETALLE_EMPLEADO FROM EMPLEADO;

--SUBCONSULTAS ANIDADAS

--BUSCAR EL 
insert into Empleado values(7, 'MARIA', 'HUERTA', 30, 'JEFE DE MARKETING', 'PUBLICIDAD');
COMMIT;

--BUSCAR EL EMPLEADO MAS GRANDE DEL DEPARTAMENTO DE PUBLICIDAD
SELECT * FROM EMPLEADO WHERE
    EDAD =(
    SELECT MIN(EDAD) 
    FROM EMPLEADO 
    WHERE DEPARTAMENTO = ('PUBLICIDAD')
    );
