--DESACTIVAR LOS TRIGGERS SIMPLES
ALTER TRIGGER TR_I_COMPUTADORA DISABLE;

--SI LOS QUIEREN VOLVER A ACTIVAR MEDIANTE SENTENCIA
ALTER TRIGGER TR_I_COMPUTADORA ENABLE;

--CREACION DE TRIGGER
CREATE OR REPLACE TRIGGER TR_MULTIPLE_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA2
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR LOS DATOS(RECUPERAR ID MEDIANTE SECUNECIA)
    SELECT S_ID_BIT.NEXTVAL,USER,SYSDATE INTO LV_ID_BIT,LV_USUARIO,LV_FECHA FROM DUAL;
    
    --VALIDACION PARA CUALQUIER MOVIMIENTO QUE PUEDA OCURRIR
    IF INSERTING THEN
        INSERT INTO BIT_COMPUTADORA2(ID_BIT,ID_COMPU2,MARCA,MODELO,RAM,PROCESADOR,PRECIO,
        MARCA_OLD,MODELO_OLD,RAM_OLD,PROCESADOR_OLD,PRECIO_OLD,
        USUARIO,FECHA_MOV,MOVIMIENTO)
        VALUES(LV_ID_BIT,:NEW.ID_COMPU2,:NEW.MARCA,:NEW.MODELO,:NEW.RAM,:NEW.PROCESADOR,:NEW.PRECIO,
        NULL,NULL,0,NULL,0,
        LV_USUARIO,LV_FECHA,'INSERT');
        
    ELSIF UPDATING THEN
        INSERT INTO BIT_COMPUTADORA2(ID_BIT,ID_COMPU2,MARCA,MODELO,RAM,PROCESADOR,PRECIO,
        MARCA_OLD,MODELO_OLD,RAM_OLD,PROCESADOR_OLD,PRECIO_OLD,
        USUARIO,FECHA_MOV,MOVIMIENTO)
        VALUES(LV_ID_BIT, :OLD.ID_COMPU2, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO,
        :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR, :OLD.PRECIO,
        LV_USUARIO,LV_FECHA,'UPDATE');
        
    ELSIF DELETING THEN
        INSERT INTO BIT_COMPUTADORA2(ID_BIT,ID_COMPU2,MARCA,MODELO,RAM,PROCESADOR,PRECIO,
        MARCA_OLD,MODELO_OLD,RAM_OLD,PROCESADOR_OLD,PRECIO_OLD,
        USUARIO,FECHA_MOV,MOVIMIENTO)
        VALUES(LV_ID_BIT, :OLD.ID_COMPU2, NULL, NULL, 0, NULL, 0,
        :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR, :OLD.PRECIO,
        LV_USUARIO,LV_FECHA,'DELETE');
        
    END IF;
END TR_MULTIPLE_COMPUTADORA;
