--DDL PARA CREAR LA TABLA EMPLEADO
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
);

--CREAR VALORES NUEVOS

INSERT INTO EMPLEADO VALUES(1,'DANIEL', 'GOMEZ', 24, 'GERENTE DE ADMINISTRACION', 'ADMINISTRACION');
COMMIT; --CONFIRMAMOS LOS CAMBIOS ACABADOS DE HACER
--UPDATE,DELETE SE DEBE CONFIRMAR EL CAMBIO INMEDIATAMENTE USANDO COMMIT (F11)

SELECT * FROM empleado;

--METODOS PARA ELIMINAR
--EJECUTAR UN DDL PARA ELIMINAR LOS REGISTROS
DELETE FROM EMPLEADO; --ELIMINA LOS REGISTROS DENTRO DE LA TABLA

--EJECUTAR UN DML PARA ELIMINAR LA TABLA
DROP TABLE EMPLEADO;


--USO DE LOS CONSTRAINT

--EJEMPLO 1 USO DE PRIMARY KEY
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2 (100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    PRIMARY KEY(ID_EMPLEADO)
    
);

--TERCERA FORMA 
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2 (100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
    
);