--OPERACIONES QUE SE MANEJAN EN SQL

--DDL->LENGUAJE PARA DEFINIR Y MODIFICAR LAS ESTRUCTURA DE LOS OBJETOS EN LAS BASE DE DATOS -> CREATE, UPDATE, ALTER Y DROP
--DML->LENGUAJE DE MANIPULACION DE DATOS -> SELECT, INSTERT, UPDATE, DELETE
--DCL->LENGUAJE DE CONTROL DE DATOS->GRAN Y REVOKE

--CREACION DE UN NUEVO USUARIO

--MODIFICAR LA SISION ACTUAL PARA LA EJECUCION DE SCRIPST: CUANDO SE EJECUTARA UNA SENTENCIA
--QUE SIGNIFICA TENER LOS PERMISOS NECESARIOS DE ORACLE PARA QUE SE REALCE, MODIFICA LA SESION Y ENTONCES PODEMOS

--EJECUTAR CUALQUIER TIPO DE OPERACION EN LA QUE PUEDA VER AFECTADA MI BASE DE DATOS
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; --EJECUTAR CON CRTL + ENTER

--CREACION DE UN USUARIO CON CONTRASENA
CREATE USER CURSOBD IDENTIFIED BY 12345;

--OTORGAR TODOS LOS PRIVILEGIOS AL NUEVO USUARIO
GRANT ALL PRIVILEGES TO CURSOBD;