/*BLOQUES PL/SQL: BLOQUES QUE PUEDEN EJECUTAR SENTENCIAS
DECLAREW |IS| AS(OPCIONAL); NO ES NECESARIO DEFINIR SIEMPRE LAS VARIABLES O CONSTANTES
BEGIN (INSTRUCCIONES): CONTIENE LAS SENTENCIAS QUE EL BLOQUE DEBE EJECUTAR
EXCEPCIONES: SE PUEDE O NO CAPTURAR EXCEPCIONES DEL SISTEMA

SINTAXIS:
DECLARE |IS| AS
BEGIN
......
EXCEPTION
EDAN;
/ <-- INDICADOR DE QUE AQUI CIERRA EL BLOQUE
*/

DECLARE --DECLARACION DE VARIABLES, CONSTANTES O CURSORES
LV_VARIABLE NUMBER := 0;
BEGIN --DONDE INICIA LA EJECUCION DE SENTENCIAS
    DBMS_OUTPUT.PUT_LINE('HOLA MUNDO DESDE BLOQUE ANONIMO PL/SQL');
END;
/ --INDICADOR, HASTA AQUI TERMINA Y HASTA AQUI DEBE EJECUTAR

DECLARE
LV_VARIABLE NUMBER := 0;
BEGIN
    LOOP
        dbms_output.put_line('VALOR DE VARIABLE: '|| LV_VARIABLE);
        LV_VARIABLE := LV_VARIABLE + 1;
        
        --SALIDA CUANDO LA VARIABLE SEA 10
        IF LV_VARIABLE = 10
            THEN EXIT;
        END IF;
    END LOOP;
END;
/

--USO DEL CICLO FOR Y LOOP
DECLARE
BEGIN
    --FOR
    FOR i IN 1..10
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DE LA VARIABLE FOR: '||i);
            EXIT WHEN i = 6;
        END LOOP;
END;
/

--USO DEL CICLO WHILE Y LOOP
DECLARE
LV_INTERADOR NUMBER := 1;
BEGIN
    WHILE LV_INTERADOR <= 6
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DEL INTERATOR CON WHILE: '||LV_INTERADOR);
            LV_INTERADOR := LV_INTERADOR + 1;
        END LOOP;
END;
/

--USO DE VARIABLE BOOLEANA Y LOOP
DECLARE
LV_VALIDADOR BOOLEAN := FALSE;
BEGIN
    FOR I IN 1..20
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DE LA VARIABLE: '||I);
            IF I = 9 THEN
                LV_VALIDADOR := TRUE;
            END IF;
                EXIT WHEN LV_VALIDADOR;
        END LOOP;
END;
/

